version: 1

# checkmarx-specific related configuration
# every value in this section is optional 
checkmarx: 
  # configure the checkmarx scan parameters for scanning this specific project
  scan:
    # configure the checkmarx scan configurations for scanning this specific project
    configs:
      # configure the SAST related configurations this specific project
      sast:
        # configure the SAST preset name used for this specific project
        presetName: 'High and Medium'
         # configure if this specific project will be run incrementally or will it run a full scan 
        incremental: 'false'
        languageMode: 'multi'
        engineVerbose: 'true'
      sca:
      kics:
